AllCops:
  TargetRubyVersion: 2.4

# TODO: enable this when Ruby 3.0 is out.
Style/FrozenStringLiteralComment:
  Enabled: false

MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 100

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false
